name: CI/CD for DevExpress XPO WinForms App

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment for your WinForms app

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Set to .NET 8.0

    - name: Configure DevExpress NuGet Source
      run: nuget sources add -Name "DevExpress NuGet Feed" -Source "https://nuget.devexpress.com/U6YRYNe1qarLOLMFwYiU2R1jQRVmex9dq9SgVPQCd4EtEuhzhU/api/v3/index.json"

    - name: Restore Dependencies
      run: dotnet restore WinAppAutomation.sln

    - name: Build the Application
      run: dotnet build WinAppAutomation.sln --configuration Release

    - name: Run Tests
      run: dotnet test PersonTests/PersonTests.csproj --configuration Release
      
    - name: Deploy via SSH
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Install OpenSSH client if not already installed
        choco install openssh -y
        
        # Use SCP to copy files to the remote machine
        scp -r .\bin\Release\net8.0\* $env:SSH_USERNAME@$env:SSH_HOST:"C:/Deployments/WinAppAutomation"

        # SSH into the remote machine to verify deployment
        ssh $env:SSH_USERNAME@$env:SSH_HOST "dir C:/Deployments/WinAppAutomation"
    
