name: CI/CD for DevExpress XPO WinForms App3
on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Set to .NET 8.0

    - name: Install NuGet
      run: |
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
        $env:Path += ";$PWD"
         
    - name: Restore Dependencies
      run: dotnet restore WinAppAutomation.sln

    - name: Build the Application
      run: dotnet build WinAppAutomation.sln --configuration Release

    - name: Run tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage"  # Collects code coverage
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Abbz290/WinAppAutomation

    - name: Deploy Application Locally
      run: |
        echo "Deploying build files locally..."
        # Ensure the destination folder exists
        if (-not (Test-Path -Path "C:\Deployments\WinAppAutomation")) {
          New-Item -Path "C:\Deployments\WinAppAutomation" -ItemType Directory
        }
        # Copy the files to the destination
        Copy-Item -Path .\WinAppAutomation.Win\bin\Release\net8.0-windows\* -Destination "C:\Deployments\WinAppAutomation\" -Recurse -Force
        echo "Deployment completed successfully."

    - name: Run the Application
      run: |
        echo "Starting the application..."
        # Start the application locally
        start C:\Deployments\WinAppAutomation\WinAppAutomation.Win.exe
        
    - name: Open the Deployed Application
      run: |
        echo "Starting the application..."
        start C:\Deployments\WinAppAutomation\WinAppAutomation.Win.exe
