name: CI/CD for DevExpress XPO WinForms App

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment for your WinForms app

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Set to .NET 8.0
    - name: Add Local NuGet Source
      run: |
        nuget sources add -Source "C:\Program Files\DevExpress 24.2\Components" -Name "Offline Packages"
    - name: Restore Dependencies
      run: dotnet restore WinAppAutomation.sln

    - name: Build the Application
      run: dotnet build WinAppAutomation.sln --configuration Release

    - name: Run Tests
      run: dotnet test PersonTests/PersonTests.csproj --configuration Release

    
