name: CI/CD for DevExpress XPO WinForms App

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Set to .NET 8.0

    - name: Install NuGet
      run: |
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
        $env:Path += ";$PWD"

    - name: Configure DevExpress NuGet Source
      run: |
        nuget sources add -Name "DevExpress NuGet Feed" -Source "https://nuget.devexpress.com/U6YRYNe1qarLOLMFwYiU2R1jQRVmex9dq9SgVPQCd4EtEuhzhU/api/v3/index.json"

    - name: Restore Dependencies
      run: dotnet restore WinAppAutomation.sln

    - name: Build the Application
      run: dotnet build WinAppAutomation.sln --configuration Release

    - name: Run Tests
      run: dotnet test PersonTests/PersonTests.csproj --configuration Release

    - name: Deploy Application Locally
      run: |
        echo "Deploying build files locally..."
        copy .\WinAppAutomation.Win\bin\Release\net8.0-windows\* C:\Deployments\WinAppAutomation\
        echo "Deployment completed successfully."

    - name: Run the Application
      run: |
        echo "Starting the application..."
        start C:\Deployments\WinAppAutomation\WinAppAutomation.Win.exe
    
