name: CI/CD for DevExpress XPO WinForms App

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment for your WinForms app

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Set to .NET 8.0

    - name: Remove Existing NuGet Source (if any)
      run: |
        nuget sources remove -Name "DevExpress Offline" || echo "No source found to remove"

    - name: Add DevExpress Offline NuGet Source
      run: |
        nuget sources add -Name "DevExpress Offline" -Source "C:\Program Files\DevExpress 24.2\Components\Offline Packages"

    - name: Restore Dependencies using nuget.config
      run: dotnet restore WinAppAutomation.sln --configfile nuget.config

    - name: Build the Application
      run: dotnet build WinAppAutomation.sln --configuration Release

    - name: Run Tests
      run: dotnet test PersonTests/PersonTests.csproj --configuration Release

    
